name: CI

on: [push, pull_request]

jobs:

  build:
    name: Compile QMPDClient
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ouuan/install-qt-action@v2.4.1
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: Compile
      run: cmake --build build
